# Generated by Django 4.2.1 on 2023-09-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permissions',
            new_name='custom_permissions',
        ),
    ]
