# Generated by Django 4.2.1 on 2023-09-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permission',
        ),
    ]
