# Generated by Django 4.2.1 on 2023-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_grouppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permissions', models.ManyToManyField(related_name='roles', to='connect.permission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
    ]
