# Generated by Django 4.2.1 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_alter_permission_options_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='connect.permission'),
        ),
    ]
